server:
  port: 8082
spring:
  application:
    name: auth-service # 应用名
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
# Eureka服务中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://192.168.0.253:10000/eureka